[package]
name = "knotes-api"
version = "0.1.0"
authors = ["akonwi <akonwi@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
validator = "0.8.0"
validator_derive = "0.8.0"
