version: "3.7"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - type: bind
        source: /data/mysql
        target: /usr/local/mysql
